### PR TITLE
Use yarn to manage npm packages, cache pip (see #84)

### PR DESCRIPTION
**Pull request by waryhermit**

### CODE REVIEW

**Comment by waryhermit** [comment]
Since deleting the node_modules folder made the changes hard to see, this pull request makes the following changes

- Caches pip installs
- Uses yarn to manage NPM packages. ([see why yarn](http://stackoverflow.com/questions/40027819/when-to-use-yarn-over-npm-what-are-the-differences))
- Retries yarn installs
- Retries pip installs
- Removes node_modules folder and adds it to .git ignore

**Review by dogi — CHANGES_REQUESTED** [review]
@waryhermit I understand your reasoning behind removing all the `node_modules`  stuff which is already in use by `BeLL-Apps`, but since we use that stuff for other processes it would be awesome if you do not remove them for now ...

**Comment by waryhermit** [comment]
@dogi 
>  but since we use that stuff for other processes it would be awesome

Please explain more. The test pass fine, so its not needed for that. And when people need the packages locally they can install them then can now use `npm install` without worrying since `node_modules` was added to the gitignore.

**Comment by waryhermit** [comment]
Though if they want the benefit of yarn they will have to install that - yarn is backwards compatible with npm but its benefits will not be realized unless everyone uses it.

**Comment by dogi** [comment]
@waryhermit do you realize that next to every install script ever written is using the npm couchapp package ;)

**Comment by dogi** [comment]
for the seek of using `yarn` in travis we can move the `node_modules` folder before install to an other place lets say `node_modules.old`

How does that sound?

**Comment by waryhermit** [comment]
@dogi OK, so your concern is not dev or travis, but deployments?

**Comment by waryhermit** [comment]
Putting all yarn stuff on hold for now since @dogi does not feel this is a good time. I will make a new pull request sometime later in the year

**Pull request closed without merging**
