### PR TITLE
test publication (connect #18)

### PR DESCRIPTION
**Pull request by prmurphy**
I am trying out my test remotely.

### CODE REVIEW

**Comment by dogi** [comment]
this PR is about issue https://github.com/ole-vi/BeLL-Apps/issues/18

**Comment by dogi** [comment]
@prmurphy there is warning in https://travis-ci.org/ole-vi/BeLL-Apps/builds/187817929 you can see it at line 779:

```
./home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py:585: DeprecationWarning: use driver.switch_to.alert instead
  warnings.warn("use driver.switch_to.alert instead", DeprecationWarning)
```

think we need to fix the error or maybe just suppress the warning ;)
cause I think that warning is disturbing and/or misleading

**Review by dogi — CHANGES_REQUESTED** [review]
https://github.com/ole-vi/BeLL-Apps/pull/45#issuecomment-269877858

**Review by waryhermit — COMMENTED** [review]
@prmurphy Overall I think it is very good. I would recommend changing as many of your sleeps as you can to explicit waits, as they are less brittle to random performance issues. As @dogi mentioned, you can also update switch to driver.switch_to.alert() because they are telling us that switch_to_alert may be removed in a later version.

**Comment by prmurphy** [comment]
I changed to switch_to.alert to avoid the error, I also added  explicit waits and a function that waits for Jquery to load (at least that's what it's supposed to do). It took the run time from a little over 2 minutes to 1 minute on my machine.

**Review by dogi — APPROVED** [review]

**Review by waryhermit — APPROVED** [review]
Looks good to me. Eventually we should probably move the check Jquery to a central shared module like bell.py

**Review by hikaruit15 — COMMENTED** [review]
@prmurphy 
I saw your comment like this:
``` 
# uncomment to test languages other than English
# dropdown = Select(driver.find_element_by_name("selectLanguage"))
 # dropdown.select_by_value("Spanish")
````
Does it work? I couldn't find the code you test for `spanish`.

**Comment by dogi** [comment]
@hikaruit15 good one +1
hmm maybe you wanna try that out @hikaruit15  ;)

**Comment by waryhermit** [comment]
It should work I think:

image


Its just selecting what language the publication is, so it doesn't change the UI any.

**Comment by hikaruit15** [comment]
hi @waryhermit,
The app will work but I mean about the test. 
Because the test get success or failure from comparing texts. 
So if you change to language to **Spanish**, the test will get failure.
```
actual = Alert(driver).text
expected = "Configurations are successfully added."
self.assertEqual(actual, expected)
```

By the way, we already had test for languages. We don't need that anymore.
In my opinion, it will be better if removing that comment or taking note that it is in process.

**Comment by waryhermit** [comment]
@hikaruit15 That doesn't change the language of the UI, its just marking what language the publication is, so it wouldn't change UI text. At least that is my understanding.

**Comment by hikaruit15** [comment]
Sorry @waryhermit.
Just checking. I misunderstood that @prmurphy changes the language of App but he just changes the language of publication.

**Comment by prmurphy** [comment]
@waryhermit and @hikaruit15  I believe that was written by @aberdean, which only happens if this is the first time Bell Apps is accessed by a user.

**Pull request merged**
