### PR TITLE
fix test name formatting (fixes #73)

### LINKED ISSUE #73: fix travis python unittest output
please change this output
```
$ python -m unittest discover tests
Link to test_feedback: https://saucelabs.com/jobs/df2cf98f5beb48d3a72265741e305392
.Link to test_language: https://saucelabs.com/jobs/87ee8043287d4394a366c8e704695f7b
.Link to test_incorrect_login: https://saucelabs.com/jobs/b6041c8be4ec401a9d86a994e9dbeba6
.Link to test_login: https://saucelabs.com/jobs/093d18a5cdf6419c86ef4f6ed7471685
.Link to test_add_new_meetup_singleday: https://saucelabs.com/jobs/5c9b3b7d7971430496ab185521fe8ecc
.Link to test_cancel_meetup: https://saucelabs.com/jobs/19a0abef54114fbd98d12b5db72d8e90
.Link to test_delete_meetup: https://saucelabs.com/jobs/31ce4db7ed854626a1551882b3c56d0f
.Link to test_invite_member: https://saucelabs.com/jobs/50133e68409d4f41859907846c56aac3
.Link to test_multiday_meetup: https://saucelabs.com/jobs/4e8856e6f2e2419d8bec0617efdf2348
.Link to test_recurring_meetup: https://saucelabs.com/jobs/32ca10c5eafb4405ba8cff92ed2dfae6
.Link to test_login: https://saucelabs.com/jobs/e327dcb6ec234d0c9d1bf54c39084198
ELink to test_add_resource: https://saucelabs.com/jobs/c10aa81609044db6896c97957111349a
.Link to test_new_collection: https://saucelabs.com/jobs/496e4b1ce77c423ab2d2d9b4859ca776
.Link to test_request_resource: https://saucelabs.com/jobs/0bc3f55691e6490e98a13da0903c7b1a
.
```
to this
```
$ python -m unittest discover tests
Link to test_feedback: https://saucelabs.com/jobs/df2cf98f5beb48d3a72265741e305392 .
Link to test_language: https://saucelabs.com/jobs/87ee8043287d4394a366c8e704695f7b .
Link to test_incorrect_login: https://saucelabs.com/jobs/b6041c8be4ec401a9d86a994e9dbeba6 .
Link to test_login: https://saucelabs.com/jobs/093d18a5cdf6419c86ef4f6ed7471685 .
Link to test_add_new_meetup_singleday: https://saucelabs.com/jobs/5c9b3b7d7971430496ab185521fe8ecc .
Link to test_cancel_meetup: https://saucelabs.com/jobs/19a0abef54114fbd98d12b5db72d8e90 .
Link to test_delete_meetup: https://saucelabs.com/jobs/31ce4db7ed854626a1551882b3c56d0f .
Link to test_invite_member: https://saucelabs.com/jobs/50133e68409d4f41859907846c56aac3 .
Link to test_multiday_meetup: https://saucelabs.com/jobs/4e8856e6f2e2419d8bec0617efdf2348 .
Link to test_recurring_meetup: https://saucelabs.com/jobs/32ca10c5eafb4405ba8cff92ed2dfae6 .
Link to test_login: https://saucelabs.com/jobs/e327dcb6ec234d0c9d1bf54c39084198 E
Link to test_add_resource: https://saucelabs.com/jobs/c10aa81609044db6896c97957111349a .
Link to test_new_collection: https://saucelabs.com/jobs/496e4b1ce77c423ab2d2d9b4859ca776 .
Link to test_request_resource: https://saucelabs.com/jobs/0bc3f55691e6490e98a13da0903c7b1a .
```

### PR DESCRIPTION
**Pull request by waryhermit**

### CODE REVIEW

**Review by sarvanivadali — APPROVED** [review]

**Review by dogi — COMMENTED** [review]
think we are on the right path
```
Link to test_feedback: https://saucelabs.com/jobs/d3eac2ef14194b829dae283b8199c3ae .Link to test_language: https://saucelabs.com/jobs/e9ebba86d1af46428dca458eb0ef1d32 .Link to test_incorrect_login: https://saucelabs.com/jobs/8654037aae7d431dbabfac3b1e71997f .Link to test_login: https://saucelabs.com/jobs/8e5adbe071244c968cc204858b53769a .Link to test_add_new_meetup_singleday: https://saucelabs.com/jobs/e2596503d6474cb9b0119b55e70884ee .Link to test_cancel_meetup: https://saucelabs.com/jobs/7c99fed5c42a4e2084bebdfbeb850860 .Link to test_delete_meetup: https://saucelabs.com/jobs/70e57ec1051148579547d0c6e21aa797 .Link to test_invite_member: https://saucelabs.com/jobs/6e9cc89bee184fa3b156bb6b940a5244 .Link to test_multiday_meetup: https://saucelabs.com/jobs/2c94a871de14405e9863f6c43592f270 .Link to test_recurring_meetup: https://saucelabs.com/jobs/330f93cf617f428aaa2519dde4da9944 .Link to test_login: https://saucelabs.com/jobs/2fcd02df00f44b05a72340f92854023f .Link to test_add_resource: https://saucelabs.com/jobs/2bb9871d883a439d918955fb821fe3de .Link to test_new_collection: https://saucelabs.com/jobs/2b91036edb7e43c5bee5b01547e38b7a .Link to test_request_resource: https://saucelabs.com/jobs/c88664b4727c41a78c381e195c0602c0 .
```
but as you can see above I think `newline`  after `.` or `E` would be awesome

**Review by dogi — CHANGES_REQUESTED** [review]
add `newline`

**Comment by waryhermit** [comment]
@dogi Would have fixed that yesterday but I couldn't see the logs still. Hows it look now?

**Comment by dogi** [comment]
@waryhermit thanks - but I looks like that did not work

**Review by dogi — APPROVED** [review]

**Pull request merged**
